name: Maven Package

env:
  DOCKER_HUB_REPO: emediongcharlie/docker

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    #  Ensure Docker is Set Up
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # #  Build the Docker Image (No Login Needed)
    # - name: Build Docker Image
    #   run: docker build -t dockerimg .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Set up Docker Buildx
      run: |
        docker buildx create --name multiarch-builder --use
        docker buildx inspect --bootstrap
        
    - name: Build and push Docker image to Docker Hub  
  run: |  
    docker buildx build --platform linux/amd64,linux/arm64 \
    -t ${{ env.DOCKER_HUB_REPO }}:latest \
    -t ${{ env.DOCKER_HUB_REPO }}:$GITHUB_SHA \
      --push .
